name: bast3d
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  custom_gallery_display: 0.5.0
  image_picker: ^0.8.9
  camera: 0.10.5+7
  arcore_flutter_plugin: 0.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/app/assets/

analyzer: 
  language: 
    enableSuperMixins: true
  strong-mode: true

